### ISSUE TITLE
During build: networkoptix-mediaserver: unrecognized service

### ISSUE THREAD

**Issue by mykter** [thehomerepot/nxwitness#10]
This is a minor thing, as ultimately the build succeeds, but I wondered if it had hung as it took a few minutes (on a slow machine) to make progress after this warning appeared:
```
Selecting previously unselected package networkoptix-mediaserver.
(Reading database ... 22182 files and directories currently installed.)
Preparing to unpack networkoptix.deb ...
mediaserver-eula license has already been accepted
Unpacking networkoptix-mediaserver (3.2.0) ...
Setting up networkoptix-mediaserver (3.2.0) ...
networkoptix-mediaserver: unrecognized service
```
One "fix" might be to add an echo prior to the install "the warning about an unrecognized service can be safely ignored"

**Comment by thehomerepot** [comment]
Try this branch
[Issue_10-networkoptix-mediaserver_unrecognized_service](https://github.com/thehomerepot/nxwitness/tree/Issue_10-networkoptix-mediaserver_unrecognized_service)

Keep in mind though, I'm modifying a .deb that was not intended to be run in a docker container. In any update, things could change within the package that may throw errors/warnings/etc. This message isn't a problem. Additionally, I'm not sure how slow the machine you're executing this on is, because this took <1 second to run after this point. It's the postinst script which is doing very little.

**Comment by thehomerepot** [comment]
Resolved.
